on:
  push:
    branch:
      - master

name: Create release

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Get tag
        id: version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Tar build
        run: tar -cf rpi-relay-controller-console.tar dist/*
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.current-version }}
          release_name: ${{ steps.version.outputs.current-version }}
          draft: false
          prerelease: false
      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rpi-relay-controller-console.tar
          asset_name: rpi-relay-controller-console.tar
          asset_content_type: application/zip
